{
  "hash": "0cc618fdbdca31bc41613147bf5d3881",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: \"Vedika Jawa\"\ndate: today\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Assignment Overview\n\n**Learning Objectives:**\n- Apply spatial operations to answer policy-relevant research questions\n- Integrate census demographic data with spatial analysis\n- Create publication-quality visualizations and maps\n- Work with spatial data from multiple sources\n- Communicate findings effectively for policy audiences\n\n---\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n### Research Question\n\n**Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?**\n\nYour analysis should identify counties that should be priorities for healthcare investment and policy intervention.\n\n### Required Analysis Steps\n\nComplete the following analysis, documenting each step with code and brief explanations:\n\n#### Step 1: Data Collection (5 points)\n\nLoad the required spatial data:\n- Pennsylvania county boundaries\n- Pennsylvania hospitals (from lecture data)\n- Pennsylvania census tracts\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(sf)\nlibrary(dplyr)\nlibrary(tigris)\nlibrary(knitr)\n\n# Load spatial data\ndata_dir <- path.expand(\"~/Downloads\")\n\ncounties  <- st_read(file.path(data_dir, \"Pennsylvania_County_Boundaries\"))\nhospitals <- st_read(file.path(data_dir, \"hospitals.geojson\"))\ndistricts <- st_read(file.path(data_dir, \"districts.geojson\"))\n\npa_tracts <- tracts(state = \"PA\", year = 2022, class = \"sf\")\n\nhospitals <- st_transform(hospitals, st_crs(counties))\ndistricts <- st_transform(districts, st_crs(counties))\npa_tracts  <- st_transform(pa_tracts,  st_crs(counties))\n\n# Check that all data loaded correctly\ndata_summary <- data.frame(\n  dataset = c(\"Counties\", \"Hospitals\", \"Districts\", \"Census tracts\"),\n  features = c(nrow(counties), nrow(hospitals), nrow(districts), nrow(pa_tracts)),\n  geometry_type = c(\n    paste(unique(st_geometry_type(counties)), collapse = \", \"),\n    paste(unique(st_geometry_type(hospitals)), collapse = \", \"),\n    paste(unique(st_geometry_type(districts)), collapse = \", \"),\n    paste(unique(st_geometry_type(pa_tracts)), collapse = \", \")\n  ),\n  crs_epsg = c(st_crs(counties)$epsg, st_crs(hospitals)$epsg, st_crs(districts)$epsg, st_crs(pa_tracts)$epsg)\n)\n\nkable(data_summary, caption = \"Loaded spatial datasets (Lab 2, Step 1)\")\n```\n:::\n\n\n**Questions to answer:**\n- How many hospitals are in your dataset?\n\n223 hospitals\n\n- How many census tracts?\n\n3,446 census tracts\n\n- What coordinate reference system is each dataset in?\n\nEeach dataset is in EPSG:3857 (WGS 84 / Pseudo-Mercator).\n---\n\n#### Step 2: Get Demographic Data \n\nUse `tidycensus` to download tract-level demographic data for Pennsylvania.\n\n**Required variables:**\n- Total population\n- Median household income\n- Population 65 years and over (you may need to sum multiple age categories)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidycensus)\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(knitr)\n\n# Get demographic data from ACS\nvars <- c(\n  total_pop = \"B01003_001\",\n  med_hh_income = \"B19013_001\",\n  # 65+ by sex (sum these)\n  m_65_66 = \"B01001_020\",\n  m_67_69 = \"B01001_021\",\n  m_70_74 = \"B01001_022\",\n  m_75_79 = \"B01001_023\",\n  m_80_84 = \"B01001_024\",\n  m_85_up = \"B01001_025\",\n  f_65_66 = \"B01001_044\",\n  f_67_69 = \"B01001_045\",\n  f_70_74 = \"B01001_046\",\n  f_75_79 = \"B01001_047\",\n  f_80_84 = \"B01001_048\",\n  f_85_up = \"B01001_049\"\n)\n\nacs_long <- get_acs(\n  geography = \"tract\",\n  state = \"PA\",\n  year = 2022,\n  survey = \"acs5\",\n  variables = vars,\n  geometry = FALSE,\n  cache_table = TRUE\n)\n\nacs_wide <- acs_long %>%\n  select(GEOID, variable, estimate) %>%\n  tidyr::pivot_wider(names_from = variable, values_from = estimate) %>%\n  mutate(\n    pop_65_plus = m_65_66 + m_67_69 + m_70_74 + m_75_79 + m_80_84 + m_85_up +\n                  f_65_66 + f_67_69 + f_70_74 + f_75_79 + f_80_84 + f_85_up\n  ) %>%\n  select(GEOID, total_pop, med_hh_income, pop_65_plus)\n\n# Join to tract boundaries\npa_tracts_demo <- pa_tracts %>%\n  left_join(acs_wide, by = \"GEOID\")\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Questions to answer (compute + show clean output)\nacs_year <- 2022\nmissing_income_tracts <- sum(is.na(acs_wide$med_hh_income))\nmedian_income_pa <- median(acs_wide$med_hh_income, na.rm = TRUE)\n\nanswers_step2 <- data.frame(\n  question = c(\n    \"ACS year used\",\n    \"Tracts with missing income data\",\n    \"Median income across all PA census tracts\"\n  ),\n  answer = c(\n    paste0(acs_year, \" (ACS 5-year, acs5)\"),\n    missing_income_tracts,\n    round(median_income_pa, 0)\n  )\n)\n\nkable(answers_step2, caption = \"Step 2 answers\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Step 2 answers\n\n|question                                  |answer                  |\n|:-----------------------------------------|:-----------------------|\n|ACS year used                             |2022 (ACS 5-year, acs5) |\n|Tracts with missing income data           |63                      |\n|Median income across all PA census tracts |70188                   |\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What year of ACS data are you using?\n\n2022 American Community Survey (ACS) 5-year estimates\n\n- How many tracts have missing income data?\n\n63 census tracts\n\n- What is the median income across all PA census tracts?\n\n$70,188\n\n---\n\n#### Step 3: Define Vulnerable Populations \n\nIdentify census tracts with vulnerable populations based on TWO criteria:\n1. Low median household income (choose an appropriate threshold)\n2. Significant elderly population (choose an appropriate threshold)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for vulnerable tracts based on your criteria\n# Income: bottom 25% of tract median household income (statewide)\nincome_threshold <- quantile(pa_tracts_demo$med_hh_income, 0.25, na.rm = TRUE)\n\n# Elderly: 65+ share >= 15% of tract population\nelderly_share_threshold <- 0.15\n\n# Create elderly share + vulnerability flag\npa_tracts_vuln <- pa_tracts_demo %>%\n  mutate(\n    elderly_share = pop_65_plus / total_pop,\n    vulnerable = !is.na(med_hh_income) &\n      !is.na(total_pop) & total_pop > 0 &\n      (med_hh_income <= income_threshold) &\n      (elderly_share >= elderly_share_threshold)\n  )\n\n# Keep only vulnerable tracts\nvulnerable_tracts <- pa_tracts_vuln %>%\n  filter(vulnerable)\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(knitr)\n\nn_vulnerable <- nrow(vulnerable_tracts)\nn_total_tracts <- nrow(pa_tracts_vuln)\n\npct_vulnerable <- 100 * n_vulnerable / n_total_tracts\n\nvuln_summary <- data.frame(\n  metric = c(\n    \"Income threshold (bottom 25% cutoff)\",\n    \"Elderly share threshold\",\n    \"Number of vulnerable tracts\",\n    \"Percent of PA tracts vulnerable\"\n  ),\n  value = c(\n    round(income_threshold, 0),\n    paste0(elderly_share_threshold * 100, \"% (65+ share)\"),\n    n_vulnerable,\n    paste0(round(pct_vulnerable, 2), \"%\")\n  )\n)\n\nkable(vuln_summary, caption = \"Vulnerability definition and results\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Vulnerability definition and results\n\n|metric                               |value           |\n|:------------------------------------|:---------------|\n|Income threshold (bottom 25% cutoff) |55924           |\n|Elderly share threshold              |15% (65+ share) |\n|Number of vulnerable tracts          |473             |\n|Percent of PA tracts vulnerable      |13.73%          |\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What income threshold did you choose and why?\n\nI defined “low income” as census tracts in the bottom quartile (25th percentile) of tract median household income in Pennsylvania. This corresponds to an income cutoff of $55,924. Using a percentile-based threshold is appropriate because it is state-specific and distribution-aware, and it targets the tracts that are most economically disadvantaged relative to other tracts in PA.\n\n- What elderly population threshold did you choose and why?\n\nI defined a “significant elderly population” as tracts where at least 15% of residents are age 65+. This threshold flags tracts with a meaningfully high concentration of older residents, who tend to have greater healthcare needs and may face mobility/access constraints, making geographic access to hospitals more consequential.\n\n- How many tracts meet your vulnerability criteria?\n\nUsing these two criteria jointly (income ≤ $55,924 and 65+ share ≥ 15%), 473 census tracts meet the vulnerability definition.\n\n- What percentage of PA census tracts are considered vulnerable by your definition?\n\nUnder this definition, 13.73% of Pennsylvania census tracts are classified as vulnerable.\n\n---\n\n#### Step 4: Calculate Distance to Hospitals \n\nFor each vulnerable tract, calculate the distance to the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(sf)\nlibrary(dplyr)\nlibrary(units)\n\n# Transform to appropriate projected CRS\nvuln_utm <- st_transform(vulnerable_tracts, 26918)\nhosp_utm <- st_transform(hospitals, 26918)\n\n# Calculate distance from each tract centroid to nearest hospital\nvuln_centroids <- st_centroid(vuln_utm)\n\n# Distance matrix (tract centroids x hospitals) in meters\ndist_m <- st_distance(vuln_centroids, hosp_utm)\n\n# Nearest hospital distance for each tract (min across hospitals)\nnearest_m <- apply(dist_m, 1, min)\n\n# Convert to miles\nnearest_miles <- set_units(nearest_m, \"m\") %>%\n  set_units(\"mi\") %>%\n  drop_units()\n\n# Add distances back to the vulnerable tracts sf object\nvuln_with_dist <- vuln_utm %>%\n  mutate(\n    dist_to_hosp_miles = nearest_miles\n  )\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(knitr)\n\navg_dist <- mean(vuln_with_dist$dist_to_hosp_miles, na.rm = TRUE)\nmax_dist <- max(vuln_with_dist$dist_to_hosp_miles, na.rm = TRUE)\nn_over_15 <- sum(vuln_with_dist$dist_to_hosp_miles > 15, na.rm = TRUE)\n\ndist_summary <- data.frame(\n  metric = c(\n    \"Average distance to nearest hospital (miles)\",\n    \"Maximum distance to nearest hospital (miles)\",\n    \"Vulnerable tracts > 15 miles from nearest hospital\"\n  ),\n  value = c(\n    round(avg_dist, 2),\n    round(max_dist, 2),\n    n_over_15\n  )\n)\n\nkable(dist_summary, caption = \"Distance to nearest hospital (vulnerable tracts)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Distance to nearest hospital (vulnerable tracts)\n\n|metric                                             | value|\n|:--------------------------------------------------|-----:|\n|Average distance to nearest hospital (miles)       |  4.05|\n|Maximum distance to nearest hospital (miles)       | 25.64|\n|Vulnerable tracts > 15 miles from nearest hospital | 21.00|\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use an appropriate projected coordinate system for Pennsylvania\n- Calculate distances in miles\n- Explain why you chose your projection\n\nI calculated distances using NAD83 / UTM Zone 18N (EPSG:26918) because it is a projected coordinate system that measures distance in meters rather than degrees. Since Pennsylvania falls largely within UTM Zone 18N, this projection minimizes distortion across the state and produces more accurate tract-to-hospital distance estimates than a geographic CRS.\n\n**Questions to answer:**\n- What is the average distance to the nearest hospital for vulnerable tracts?\n\nOn average, vulnerable census tracts are located 4.05 miles from the nearest hospital.\n\n- What is the maximum distance?\n\nThe maximum distance to the nearest hospital among vulnerable tracts is 25.64 miles.\n\n- How many vulnerable tracts are more than 15 miles from the nearest hospital?\n\n21 vulnerable census tracts are located more than 15 miles from the nearest hospital.\n\n---\n\n#### Step 5: Identify Underserved Areas \n\nDefine \"underserved\" as vulnerable tracts that are more than 15 miles from the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n\n# Create underserved variable\nunderserved_threshold <- 15\n\nvuln_with_dist <- vuln_with_dist %>%\n  mutate(\n    underserved = dist_to_hosp_miles > underserved_threshold\n  )\n\nunderserved_tracts <- vuln_with_dist %>%\n  filter(underserved)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(knitr)\n\nn_underserved <- nrow(underserved_tracts)\nn_vulnerable_total <- nrow(vuln_with_dist)\n\npct_vulnerable_underserved <- 100 * n_underserved / n_vulnerable_total\n\nunderserved_summary <- data.frame(\n  metric = c(\n    \"Underserved threshold (miles)\",\n    \"Number of underserved tracts\",\n    \"Percent of vulnerable tracts underserved\"\n  ),\n  value = c(\n    underserved_threshold,\n    n_underserved,\n    paste0(round(pct_vulnerable_underserved, 2), \"%\")\n  )\n)\n\nkable(underserved_summary, caption = \"Underserved tracts summary\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Underserved tracts summary\n\n|metric                                   |value |\n|:----------------------------------------|:-----|\n|Underserved threshold (miles)            |15    |\n|Number of underserved tracts             |21    |\n|Percent of vulnerable tracts underserved |4.44% |\n\n\n:::\n:::\n\n\n\n**Questions to answer:**\n- How many tracts are underserved?\n\n21 census tracts.\n\n- What percentage of vulnerable tracts are underserved?\n\n4.44% of all vulnerable census tracts.\n\n- Does this surprise you? Why or why not?\n\nI am somewhat not surprised. While Pennsylvania contains large rural areas where hospitals are relatively sparse, the state overall has a fairly dense healthcare infrastructure, especially in urban and suburban regions. As a result, only a small share of vulnerable tracts are located far from hospitals. However, the existence of even a small number of underserved tracts is important, as these communities may face meaningful geographic barriers to care and could benefit from targeted policy interventions.\n\n---\n\n#### Step 6: Aggregate to County Level\n\nUse spatial joins and aggregation to calculate county-level statistics about vulnerable populations and hospital access.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(sf)\nlibrary(dplyr)\nlibrary(knitr)\n\n# Spatial join tracts to counties\ncounties_utm <- st_transform(counties, st_crs(vuln_with_dist))\n\ntracts_with_county <- st_join(\n  vuln_with_dist,\n  counties_utm,\n  join = st_within,\n  left = FALSE\n)\n\n# Aggregate statistics by county\ncounty_stats <- tracts_with_county %>%\n  st_drop_geometry() %>%\n  group_by(COUNTY_NAM) %>%\n  summarise(\n    vulnerable_tracts = n(),\n    underserved_tracts = sum(underserved, na.rm = TRUE),\n    pct_vulnerable_underserved = 100 * underserved_tracts / vulnerable_tracts,\n    avg_dist_to_hosp_miles = mean(dist_to_hosp_miles, na.rm = TRUE),\n    total_vulnerable_pop = sum(total_pop, na.rm = TRUE),\n    .groups = \"drop\"\n  ) %>%\n  rename(county = COUNTY_NAM) %>%\n  arrange(desc(pct_vulnerable_underserved))\n\nkable(\n  head(county_stats, 10),\n  digits = 2,\n  caption = \"Top 10 counties by percent underserved among vulnerable tracts\"\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Top 5 counties by % underserved vulnerable tracts\ntop5_pct_underserved <- county_stats %>%\n  slice_max(pct_vulnerable_underserved, n = 5)\n\nkable(\n  top5_pct_underserved,\n  digits = 2,\n  caption = \"Top 5 counties: highest % underserved among vulnerable tracts\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 5 counties: highest % underserved among vulnerable tracts\n\n|county     | vulnerable_tracts| underserved_tracts| pct_vulnerable_underserved| avg_dist_to_hosp_miles| total_vulnerable_pop|\n|:----------|-----------------:|------------------:|--------------------------:|----------------------:|--------------------:|\n|CAMERON    |                 1|                  1|                     100.00|                  18.68|                 1988|\n|MONROE     |                 1|                  1|                     100.00|                  17.68|                 1299|\n|CLEARFIELD |                 5|                  3|                      60.00|                  13.77|                16501|\n|BRADFORD   |                 3|                  1|                      33.33|                  11.19|                11547|\n|ERIE       |                10|                  1|                      10.00|                   4.03|                29721|\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Counties with the most vulnerable people living far from hospitals (>15 miles)\nfar_pop_by_county <- tracts_with_county %>%\n  filter(underserved) %>%\n  st_drop_geometry() %>%\n  group_by(COUNTY_NAM) %>%\n  summarise(\n    underserved_vulnerable_pop = sum(total_pop, na.rm = TRUE),\n    underserved_tracts = n(),\n    .groups = \"drop\"\n  ) %>%\n  rename(county = COUNTY_NAM) %>%\n  arrange(desc(underserved_vulnerable_pop))\n\nkable(\n  head(far_pop_by_county, 10),\n  caption = \"Counties with most vulnerable people in underserved tracts (>15 miles)\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Counties with most vulnerable people in underserved tracts (>15 miles)\n\n|county     | underserved_vulnerable_pop| underserved_tracts|\n|:----------|--------------------------:|------------------:|\n|CLEARFIELD |                       8313|                  3|\n|BRADFORD   |                       5466|                  1|\n|CAMERON    |                       1988|                  1|\n|ERIE       |                       1320|                  1|\n|MONROE     |                       1299|                  1|\n\n\n:::\n:::\n\n\n**Required county-level statistics:**\n- Number of vulnerable tracts\n- Number of underserved tracts  \n- Percentage of vulnerable tracts that are underserved\n- Average distance to nearest hospital for vulnerable tracts\n- Total vulnerable population\n\n**Questions to answer:**\n- Which 5 counties have the highest percentage of underserved vulnerable tracts?\n\nThe counties with the highest percentage of underserved vulnerable tracts are Cameron, Monroe, Clearfield, Bradford, and Erie. Cameron and Monroe each have 100% of their vulnerable tracts classified as underserved, meaning all vulnerable tracts in those counties are located more than 15 miles from the nearest hospital. Clearfield follows with 60%, Bradford with 33.3%, and Erie with 10%.\n\n- Which counties have the most vulnerable people living far from hospitals?\n\nThe counties with the largest vulnerable populations living more than 15 miles from a hospital are Clearfield, Bradford, Cameron, Erie, and Monroe. Among these, Clearfield County has the highest underserved vulnerable population (8,313 people), followed by Bradford County (5,466). The remaining counties have smaller but still notable vulnerable populations living far from healthcare facilities.\n\n- Are there any patterns in where underserved counties are located?\n\nThere appears to be a clear geographic pattern in the distribution of underserved counties. Most of the counties identified, including Cameron, Clearfield, and Bradford, are located in rural or sparsely populated regions of northern and central Pennsylvania. These areas tend to have lower population density and fewer healthcare facilities, which increases travel distance to hospitals. In contrast, more urban counties such as Allegheny do not show high levels of underserved vulnerable tracts, likely due to greater healthcare infrastructure and hospital availability.\n\n---\n\n#### Step 7: Create Summary Table \n\nCreate a professional table showing the top 10 priority counties for healthcare investment.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(knitr)\nlibrary(scales)\n\n# Create and format priority counties table\npriority_counties <- county_stats %>%\n  mutate(\n    priority_score = total_vulnerable_pop * (pct_vulnerable_underserved / 100)\n  ) %>%\n  arrange(desc(priority_score)) %>%\n  slice_head(n = 10) %>%\n  transmute(\n    County = county,\n    `Vulnerable tracts` = vulnerable_tracts,\n    `Underserved tracts` = underserved_tracts,\n    `% vulnerable underserved` = percent(pct_vulnerable_underserved / 100, accuracy = 0.1),\n    `Avg distance to hospital (miles)` = round(avg_dist_to_hosp_miles, 2),\n    `Total vulnerable population` = comma(total_vulnerable_pop),\n    `Priority score` = comma(round(priority_score))\n  )\n\nkable(\n  priority_counties,\n  caption = \"Top 10 counties ranked by priority score for healthcare investment\",\n  align = \"lcccccc\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 10 counties ranked by priority score for healthcare investment\n\n|County     | Vulnerable tracts | Underserved tracts | % vulnerable underserved | Avg distance to hospital (miles) | Total vulnerable population | Priority score |\n|:----------|:-----------------:|:------------------:|:------------------------:|:--------------------------------:|:---------------------------:|:--------------:|\n|CLEARFIELD |         5         |         3          |          60.0%           |              13.77               |           16,501            |     9,901      |\n|BRADFORD   |         3         |         1          |          33.3%           |              11.19               |           11,547            |     3,849      |\n|ERIE       |        10         |         1          |          10.0%           |               4.03               |           29,721            |     2,972      |\n|CAMERON    |         1         |         1          |          100.0%          |              18.68               |            1,988            |     1,988      |\n|MONROE     |         1         |         1          |          100.0%          |              17.68               |            1,299            |     1,299      |\n|ADAMS      |         1         |         0          |           0.0%           |               0.19               |            3,908            |       0        |\n|ALLEGHENY  |        69         |         0          |           0.0%           |               2.29               |           173,033           |       0        |\n|ARMSTRONG  |         2         |         0          |           0.0%           |               2.78               |            6,776            |       0        |\n|BEAVER     |        12         |         0          |           0.0%           |               2.85               |           27,306            |       0        |\n|BEDFORD    |         2         |         0          |           0.0%           |               4.31               |            8,091            |       0        |\n\n\n:::\n:::\n\n\nI ranked counties using a priority score based on the total vulnerable population multiplied by the share of vulnerable tracts that are underserved (defined as more than 15 miles from the nearest hospital). Although the table shows the top ten counties, only the first five have positive priority scores because they contain underserved vulnerable tracts under this definition. The remaining counties appear due to the requirement to list ten counties, but they do not have underserved tracts. Overall, this suggests that geographic barriers to hospital access are concentrated in a relatively small number of Pennsylvania counties rather than being widespread across the state.\n\n**Requirements:**\n- Use `knitr::kable()` or similar for formatting\n- Include descriptive column names\n- Format numbers appropriately (commas for population, percentages, etc.)\n- Add an informative caption\n- Sort by priority (you decide the metric)\n\n---\n\n## Part 2: Comprehensive Visualization \n\nUsing the skills from Week 3 (Data Visualization), create publication-quality maps and charts.\n\n### Map 1: County-Level Choropleth \n\nCreate a choropleth map showing healthcare access challenges at the county level.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(sf)\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(scales)\n\n# Create county-level access map\ncounties_map <- counties_utm %>%\n  left_join(county_stats, by = c(\"COUNTY_NAM\" = \"county\"))\n\nhosp_map <- st_transform(hospitals, st_crs(counties_map))\n\nggplot() +\n  geom_sf(\n    data = counties_map,\n    aes(fill = pct_vulnerable_underserved),\n    color = \"white\",\n    linewidth = 0.2\n  ) +\n  geom_sf(\n    data = hosp_map,\n    color = \"black\",\n    size = 0.8,\n    alpha = 0.7\n  ) +\n  scale_fill_viridis_c(\n    option = \"C\",\n    direction = 1,\n    name = \"% vulnerable tracts\\nunderserved\",\n    labels = function(x) paste0(round(x, 1), \"%\")\n  ) +\n  labs(\n    title = \"Healthcare Access Challenges in Pennsylvania\",\n    subtitle = \"County-level share of vulnerable census tracts that are underserved (>15 miles from a hospital)\",\n    caption = \"Vulnerability defined as bottom-25% median household income and 65+ share ≥ 15% (ACS 2022). Hospitals shown as points.\"\n  ) +\n  coord_sf() +\n  theme_void() +\n  theme(\n    legend.position = \"right\",\n    plot.title = element_text(face = \"bold\"),\n    plot.subtitle = element_text(size = 10),\n    plot.caption = element_text(size = 7)\n  )\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\nThe choropleth map highlights county-level variation in healthcare access by showing the share of vulnerable census tracts that are underserved (defined as more than 15 miles from the nearest hospital). Most counties have low or zero underserved shares, indicating relatively good geographic access to hospitals. However, a small number of counties, particularly Clearfield, Bradford, Cameron, and Monroe, show elevated underserved rates, suggesting localized access challenges. Hospital locations are heavily clustered in urban areas, which helps explain why underserved tracts are more concentrated in rural counties.\n\n**Requirements:**\n- Fill counties by percentage of vulnerable tracts that are underserved\n- Include hospital locations as points\n- Use an appropriate color scheme\n- Include clear title, subtitle, and caption\n- Use `theme_void()` or similar clean theme\n- Add a legend with formatted labels\n\n---\n\n### Map 2: Detailed Vulnerability Map \n\nCreate a map highlighting underserved vulnerable tracts.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(sf)\nlibrary(dplyr)\nlibrary(ggplot2)\n\n# Create detailed tract-level map\ncounties_map2 <- st_transform(counties, 26918)\nhosp_map2 <- st_transform(hospitals, 26918)\n\nvuln_map2 <- vuln_with_dist \n\nunderserved_sf <- vuln_map2 %>% filter(underserved)\nvulnerable_not_underserved_sf <- vuln_map2 %>% filter(!underserved)\n\nggplot() +\n  geom_sf(data = counties_map2, fill = NA, color = \"grey60\", linewidth = 0.25) +\n  \n  geom_sf(\n    data = vulnerable_not_underserved_sf,\n    fill = \"grey85\",\n    color = NA,\n    alpha = 0.6\n  ) +\n  \n  geom_sf(\n    data = underserved_sf,\n    fill = \"red3\",\n    color = NA,\n    alpha = 0.8\n  ) +\n  \n  geom_sf(\n    data = hosp_map2,\n    color = \"black\",\n    size = 0.8,\n    alpha = 0.7\n  ) +\n  \n  labs(\n    title = \"Underserved Vulnerable Census Tracts in Pennsylvania\",\n    subtitle = \"Underserved = vulnerable tracts located more than 15 miles from the nearest hospital\",\n    caption = \"Vulnerability defined as bottom-25% median household income and 65+ share ≥ 15% (ACS 2022). Hospitals shown as points.\"\n  ) +\n  theme_void() +\n  theme(\n    plot.title = element_text(face = \"bold\"),\n    plot.subtitle = element_text(size = 10),\n    plot.caption = element_text(size = 8)\n  )\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\nThis map highlights vulnerable census tracts that are also geographically underserved, defined as being more than 15 miles from the nearest hospital. Most underserved tracts appear in rural parts of Pennsylvania, particularly in north-central and western counties, where hospital density is lower and travel distances are greater. In contrast, urban regions show dense hospital clustering and few underserved tracts. Overall, the map suggests that healthcare access disparities are driven largely by geographic isolation rather than a lack of vulnerable populations statewide.\n\n**Requirements:**\n- Show underserved vulnerable tracts in a contrasting color\n- Include county boundaries for context\n- Show hospital locations\n- Use appropriate visual hierarchy (what should stand out?)\n- Include informative title and subtitle\n\n---\n\n### Chart: Distribution Analysis\n\nCreate a visualization showing the distribution of distances to hospitals for vulnerable populations.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\n# Create distribution visualization\n\nggplot(vuln_with_dist, aes(x = dist_to_hosp_miles)) +\n  geom_histogram(\n    bins = 30,\n    fill = \"steelblue\",\n    color = \"white\",\n    alpha = 0.8\n  ) +\n  geom_density(\n    color = \"darkred\",\n    linewidth = 1.1,\n    alpha = 0.6\n  ) +\n  geom_vline(\n    xintercept = 15,\n    linetype = \"dashed\",\n    color = \"black\",\n    linewidth = 1\n  ) +\n  labs(\n    title = \"Distribution of Distance to Nearest Hospital for Vulnerable Census Tracts\",\n    subtitle = \"Dashed line indicates underserved threshold (15 miles)\",\n    x = \"Distance to nearest hospital (miles)\",\n    y = \"Number of vulnerable tracts\",\n    caption = \"Distances calculated using tract centroids and projected CRS (EPSG:26918).\"\n  ) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(face = \"bold\"),\n    plot.subtitle = element_text(size = 10),\n    plot.caption = element_text(size = 8)\n  )\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\nThe distribution shows that most vulnerable tracts are located relatively close to hospitals, with distances clustering below 10 miles. However, a small tail of tracts exceeds the 15-mile threshold, indicating localized geographic access challenges that disproportionately affect rural vulnerable populations.\n\n**Suggested chart types:**\n- Histogram or density plot of distances\n- Box plot comparing distances across regions\n- Bar chart of underserved tracts by county\n- Scatter plot of distance vs. vulnerable population size\n\n**Requirements:**\n- Clear axes labels with units\n- Appropriate title\n- Professional formatting\n- Brief interpretation (1-2 sentences as a caption or in text)\n\n---\n\n## Part 3: Bring Your Own Data Analysis \n\nChoose your own additional spatial dataset and conduct a supplementary analysis.\n\n### Challenge Options\n\nChoose ONE of the following challenge exercises, or propose your own research question using OpenDataPhilly data (https://opendataphilly.org/datasets/). \n\n**Note these are just loose suggestions to spark ideas - follow or make your own as the data permits and as your ideas evolve. This analysis should include bringing in your own dataset, ensuring the projection/CRS of your layers align and are appropriate for the analysis (not lat/long or geodetic coordinate systems). The analysis portion should include some combination of spatial and attribute operations to answer a relatively straightforward question**\n\n---\n\n#### Education & Youth Services\n\n**Option A: Educational Desert Analysis**\n- **Data:** Schools, Libraries, Recreation Centers, Census tracts (child population)\n- **Question:** \"Which neighborhoods lack adequate educational infrastructure for children?\"\n- **Operations:** Buffer schools/libraries (0.5 mile walking distance), identify coverage gaps, overlay with child population density\n- **Policy relevance:** School district planning, library placement, after-school program siting\n\n**Option B: School Safety Zones**\n- **Data:** Schools, Crime Incidents, Bike Network\n- **Question:** \"Are school zones safe for walking/biking, or are they crime hotspots?\"\n- **Operations:** Buffer schools (1000ft safety zone), spatial join with crime incidents, assess bike infrastructure coverage\n- **Policy relevance:** Safe Routes to School programs, crossing guard placement\n\n---\n\n#### Environmental Justice\n\n**Option C: Green Space Equity** \n- **Data:** Parks, Street Trees, Census tracts (race/income demographics)\n- **Question:** \"Do low-income and minority neighborhoods have equitable access to green space?\"\n- **Operations:** Buffer parks (10-minute walk = 0.5 mile), calculate tree canopy or park acreage per capita, compare by demographics\n- **Policy relevance:** Climate resilience, environmental justice, urban forestry investment\n---\n\n#### Public Safety & Justice\n\n**Option D: Crime & Community Resources**\n- **Data:** Crime Incidents, Recreation Centers, Libraries, Street Lights\n- **Question:** \"Are high-crime areas underserved by community resources?\"\n- **Operations:** Aggregate crime counts to census tracts or neighborhoods, count community resources per area, spatial correlation analysis\n- **Policy relevance:** Community investment, violence prevention strategies\n---\n\n#### Infrastructure & Services\n\n**Option E: Polling Place Accessibility**\n- **Data:** Polling Places, SEPTA stops, Census tracts (elderly population, disability rates)\n- **Question:** \"Are polling places accessible for elderly and disabled voters?\"\n- **Operations:** Buffer polling places and transit stops, identify vulnerable populations, find areas lacking access\n- **Policy relevance:** Voting rights, election infrastructure, ADA compliance\n\n---\n\n#### Health & Wellness\n\n**Option F: Recreation & Population Health**\n- **Data:** Recreation Centers, Playgrounds, Parks, Census tracts (demographics)\n- **Question:** \"Is lack of recreation access associated with vulnerable populations?\"\n- **Operations:** Calculate recreation facilities per capita by neighborhood, buffer facilities for walking access, overlay with demographic indicators\n- **Policy relevance:** Public health investment, recreation programming, obesity prevention\n\n---\n\n#### Emergency Services\n\n**Option G: EMS Response Coverage**\n- **Data:** Fire Stations, EMS stations, Population density, High-rise buildings\n- **Question:** \"Are population-dense areas adequately covered by emergency services?\"\n- **Operations:** Create service area buffers (5-minute drive = ~2 miles), assess population coverage, identify gaps in high-density areas\n- **Policy relevance:** Emergency preparedness, station siting decisions\n\n---\n\n#### Arts & Culture\n\n**Option H: Cultural Asset Distribution**\n- **Data:** Public Art, Museums, Historic sites/markers, Neighborhoods\n- **Question:** \"Do all neighborhoods have equitable access to cultural amenities?\"\n- **Operations:** Count cultural assets per neighborhood, normalize by population, compare distribution across demographic groups\n- **Policy relevance:** Cultural equity, tourism, quality of life, neighborhood identity\n\n---\n\n### Data Sources\n\n**OpenDataPhilly:** https://opendataphilly.org/datasets/\n- Most datasets available as GeoJSON, Shapefile, or CSV with coordinates\n- Always check the Metadata for a data dictionary of the fields.\n\n**Additional Sources:**\n- **Pennsylvania Open Data:** https://data.pa.gov/\n- **Census Bureau (via tidycensus):** Demographics, economic indicators, commute patterns\n- **TIGER/Line (via tigris):** Geographic boundaries\n\n### Recommended Starting Points\n\n**If you're feeling confident:** Choose an advanced challenge with multiple data layers. \n**If you are a beginner, choose something more manageable that helps you understand the basics**\n\n\n**If you have a different idea:** Propose your own question! Just make sure:\n- You can access the spatial data\n- You can perform at least 2 spatial operations\n\n### Your Analysis\n\n**Your Task:**\n\n1. **Find and load additional data**\n   - Document your data source\n   - Check and standardize the CRS\n   - Provide basic summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(sf)\nlibrary(dplyr)\nlibrary(knitr)\n\n# Load your additional dataset\ndata_dir <- path.expand(\"~/Downloads\")\nppr_path <- file.path(data_dir, \"PPR_Program_Sites.geojson\")\n\nprogram_sites_raw <- st_read(ppr_path, quiet = TRUE)\n\nprogram_sites <- st_transform(program_sites_raw, st_crs(pa_tracts))\n\n# Basic summary stats\nppr_summary <- data.frame(\n  dataset = \"PPR Program Sites\",\n  features = nrow(program_sites),\n  geometry_type = paste(unique(st_geometry_type(program_sites)), collapse = \", \"),\n  crs_epsg = st_crs(program_sites)$epsg\n)\n\nkable(ppr_summary, caption = \"Additional dataset summary: Parks & Recreation Program Sites\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Additional dataset summary: Parks & Recreation Program Sites\n\n|dataset           | features|geometry_type | crs_epsg|\n|:-----------------|--------:|:-------------|--------:|\n|PPR Program Sites |      171|POINT         |     3857|\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What dataset did you choose and why?\n\nI used the Parks & Recreation Program Sites dataset from OpenDataPhilly. I chose this dataset because it captures recreation centers, playgrounds, and community facilities that can influence neighborhood health and well-being. Since my main analysis focused on healthcare access, this dataset allows me to explore whether underserved or vulnerable areas also face gaps in recreation resources.\n\n- What is the data source and date?\n\nThe dataset was obtained from OpenDataPhilly and maintained by the City of Philadelphia Parks & Recreation department. According to the associated GitHub repository, the dataset was last updated approximately 2 months ago. \n\n- How many features does it contain?\n\n171 features.\n\n- What CRS is it in? Did you need to transform it?\n\nThe dataset is stored in EPSG:3857 (Web Mercator). To ensure consistency with the rest of my spatial analysis, I transformed it into the same projected CRS used for the census tract dataset.\n\n---\n\n2. **Pose a research question**\n\nWrite a clear research statement that your analysis will answer.\n\nAre vulnerable census tracts with poor hospital access also underserved by recreation and community program sites in Philadelphia?\n\n**Examples:**\n- \"Do vulnerable tracts have adequate public transit access to hospitals?\"\n- \"Are EMS stations appropriately located near vulnerable populations?\"\n- \"Do areas with low vehicle access have worse hospital access?\"\n\n---\n\n3. **Conduct spatial analysis**\n\nUse at least TWO spatial operations to answer your research question.\n\n**Required operations (choose 2+):**\n- Buffers\n- Spatial joins\n- Spatial filtering with predicates\n- Distance calculations\n- Intersections or unions\n- Point-in-polygon aggregation\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(sf)\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(knitr)\n\n\nppr <- program_sites\n\n# 2) Choose projected CRS for distance/buffers\nepsg_proj <- 26918\n\ntracts_proj <- st_transform(pa_tracts_demo, epsg_proj)\nppr_proj    <- st_transform(ppr, epsg_proj)\n\n# 3) Filter to Philadelphia County tracts\nphilly_tracts <- tracts_proj %>%\n  filter(COUNTYFP == \"101\")\n\n# 2) Create vulnerability flag on the FULL tract dataset (statewide cutoff)\ntracts_proj <- tracts_proj %>%\n  mutate(pct_65_plus = pop_65_plus / total_pop)\n\nincome_cutoff <- quantile(tracts_proj$med_hh_income, 0.25, na.rm = TRUE)\n\ntracts_proj <- tracts_proj %>%\n  mutate(is_vulnerable = (med_hh_income <= income_cutoff) & (pct_65_plus >= 0.15))\n\n# 3) Filter to Philadelphia County tracts\nphilly_tracts <- tracts_proj %>%\n  filter(COUNTYFP == \"101\")\n\n# 4) Keep only vulnerable Philly tracts\nphilly_vulnerable <- philly_tracts %>%\n  filter(is_vulnerable == TRUE)\n\n# 5) Define “access” to PPR sites using a walking-distance buffer (0.5 mile)\nwalk_miles  <- 0.5\nwalk_meters <- walk_miles * 1609.34\n\nppr_buffer <- st_buffer(ppr_proj, dist = walk_meters)\n\n# 6) Spatial operation: mark vulnerable tracts as having access if they intersect ANY buffer\nhas_access <- lengths(st_intersects(philly_vulnerable, ppr_buffer)) > 0\n\nphilly_vulnerable_access <- philly_vulnerable %>%\n  mutate(ppr_access = if_else(has_access, \"Access within 0.5 mi\", \"No access within 0.5 mi\"))\n\n# 7) (Second spatial operation) Point-in-polygon count:\n# count how many PPR sites fall inside each vulnerable tract\nppr_in_tract <- st_join(ppr_proj, philly_vulnerable_access, join = st_within)\n\nppr_counts <- ppr_in_tract %>%\n  st_drop_geometry() %>%\n  count(GEOID, name = \"ppr_sites_in_tract\")\n\nphilly_vulnerable_access <- philly_vulnerable_access %>%\n  left_join(ppr_counts, by = \"GEOID\") %>%\n  mutate(ppr_sites_in_tract = if_else(is.na(ppr_sites_in_tract), 0L, ppr_sites_in_tract))\n\n# 8) Summary table\nn_vuln <- nrow(philly_vulnerable_access)\nn_with <- sum(philly_vulnerable_access$ppr_access == \"Access within 0.5 mi\")\nn_without <- sum(philly_vulnerable_access$ppr_access == \"No access within 0.5 mi\")\n\naccess_summary <- data.frame(\n  metric = c(\n    \"Walking access threshold\",\n    \"Vulnerable tracts (Philadelphia)\",\n    \"Vulnerable tracts WITH PPR access\",\n    \"Vulnerable tracts WITHOUT PPR access\",\n    \"Percent with access\",\n    \"Percent without access\"\n  ),\n  value = c(\n    paste0(walk_miles, \" miles\"),\n    n_vuln,\n    n_with,\n    n_without,\n    paste0(round(100 * n_with / n_vuln, 2), \"%\"),\n    paste0(round(100 * n_without / n_vuln, 2), \"%\")\n  )\n)\n\nkable(access_summary, caption = \"PPR access summary for vulnerable Philadelphia census tracts\")\n```\n\n::: {.cell-output-display}\n\n\nTable: PPR access summary for vulnerable Philadelphia census tracts\n\n|metric                               |value     |\n|:------------------------------------|:---------|\n|Walking access threshold             |0.5 miles |\n|Vulnerable tracts (Philadelphia)     |59        |\n|Vulnerable tracts WITH PPR access    |55        |\n|Vulnerable tracts WITHOUT PPR access |4         |\n|Percent with access                  |93.22%    |\n|Percent without access               |6.78%     |\n\n\n:::\n\n```{.r .cell-code}\n# 9) Map (add background Philly tracts so it looks like the \"full Philly\" map)\nggplot() +\n  # Background: all Philly tracts in light/neutral outline\n  geom_sf(data = philly_tracts, fill = \"white\", color = \"grey80\", linewidth = 0.15) +\n  \n  # Foreground: vulnerable tracts colored by access\n  geom_sf(data = philly_vulnerable_access, aes(fill = ppr_access),\n          color = \"white\", linewidth = 0.15) +\n  \n  # PPR sites as points\n  geom_sf(data = ppr_proj, color = \"black\", size = 1, alpha = 0.7) +\n  \n  scale_fill_manual(values = c(\n    \"No access within 0.5 mi\" = \"#d73027\",\n    \"Access within 0.5 mi\" = \"#1a9850\"\n  )) +\n  labs(\n    title = \"Access to Parks & Recreation Program Sites for Vulnerable Census Tracts (Philadelphia County)\",\n    subtitle = \"Vulnerable = bottom-25% income (statewide) AND 65+ share ≥ 15% (ACS 2022); Access = within 0.5-mile buffer\",\n    caption = \"PPR program sites shown as points. Tracts shown for Philadelphia County.\",\n    fill = \"PPR access\"\n  ) +\n  theme_void() +\n  theme(\n    plot.title = element_text(size = 18, face = \"bold\"),\n    plot.subtitle = element_text(size = 11),\n    legend.position = \"right\"\n  )\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n**Analysis requirements:**\n- Clear code comments explaining each step\n- Appropriate CRS transformations\n- Summary statistics or counts\n- At least one map showing your findings\n- Brief interpretation of results (3-5 sentences)\n\n**Your interpretation:**\n\nTo assess access to recreational resources, I created a 0.5-mile walking buffer around Parks & Recreation Program (PPR) sites and examined which vulnerable census tracts intersected these buffers. The results show that most vulnerable tracts have nearby access: 55 out of 59 tracts (93.22%) fall within walking distance, while 4 tracts (6.78%) do not.\n\nThe spatial pattern suggests that PPR sites are fairly well distributed across Philadelphia, providing broad coverage for vulnerable populations. At the same time, the small number of tracts without access appear geographically concentrated, indicating localized gaps where residents may face reduced opportunities for nearby recreation. Overall, the analysis points to generally strong accessibility but highlights specific areas where additional facilities or targeted investment could improve equity in access.\n\n\n## Finally - A few comments about your incorporation of feedback!\nTake a few moments to clean up your markdown document and then write a line or two or three about how you may have incorporated feedback that you recieved after your first assignment. \n\nAfter my first assignment, I received feedback that my website was not rendering properly, which forced me to complete parts of the work in Google Colab. For this submission, I made sure the Quarto site compiled correctly from the start and verified that all outputs displayed as intended. I also incorporated formatting feedback by suppressing unnecessary console messages using chunk options (message: false, warning: false, results: 'hide') to improve readability. Finally, I used kable to present summary tables more cleanly, which helped make the results easier to interpret for the audience.\n\n---\n\n## Submission Requirements\n\n**What to submit:**\n\n1. **Rendered HTML document posted to your course portfolio** with all code, outputs, maps, and text\n   - Use `embed-resources: true` in YAML so it's a single file\n   - All code should run without errors\n   - All maps and charts should display correctly\n2. Submit the correct and working links of your assignment on Canvas\n\n---\n\n",
    "supporting": [
      "lab2_template_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}